<?php
namespace BakerStreet\ComingSoon;

defined('ABSPATH') || exit;

use BakerStreet\ComingSoon\Admin\Settings;
use BakerStreet\ComingSoon\Front\Maintenance;

final class Plugin {
    public const OPTION_KEY = 'bs_coming_soon_options';

    public static function init(): void {
        // Admin
        if (is_admin()) {
            Settings::init();
        }

        // Frontend maintenance intercept
        Maintenance::init();

        // Provide an admin notice if /wartungsmodus can't be created
        add_action('admin_notices', [__CLASS__, 'admin_notices']);
    }

    public static function on_activate(): void {
        // Ensure public endpoint exists
        self::ensure_public_endpoint_files();

        // Flush rewrite rules just in case (not strictly needed)
        if (function_exists('flush_rewrite_rules')) {
            flush_rewrite_rules(false);
        }
    }

    public static function on_deactivate(): void {
        // Intentionally keep /wartungsmodus files.
        // Still flush rewrite rules for cleanliness.
        if (function_exists('flush_rewrite_rules')) {
            flush_rewrite_rules(false);
        }
    }

    public static function defaults(): array {
        return [
            'enabled' => '1',
            'headline' => 'Website im Umbau',
            'subline' => "Unsere Website wird heute für einen kurzen Zeitraum umgestellt.\nWährenddessen sind wir selbstverständlich weiterhin per E-Mail oder Telefon für Sie erreichbar.",
            'phone_label' => '044 362 84 84',
            'phone_href'  => '0443628484',
            'email' => 'ief@ief-zh.ch',

            'logo_url' => '',
            'brand_text' => 'IEF',
            'brand_tagline' => 'Institut für systemische Entwicklung\nund Fortbildung',

            'bg_color' => '#FFEA3D',
            'text_color' => '#2B2B2B',
            'card_bg' => '#FFFFFF',
            'font_family' => 'Whitney, sans-serif',
            'max_width' => 720,
        ];
    }

    public static function get_options(): array {
        $saved = get_option(self::OPTION_KEY, []);
        $saved = is_array($saved) ? $saved : [];
        return array_merge(self::defaults(), $saved);
    }

    public static function update_options(array $opts): void {
        update_option(self::OPTION_KEY, $opts, false);
        // Keep /wartungsmodus in sync with the latest template (and ensure it exists)
        self::ensure_public_endpoint_files();
    }

    /**
     * Creates/updates /wartungsmodus files in the web root.
     * Keeps them even when the plugin is deactivated.
     */
    public static function ensure_public_endpoint_files(): void {
        // get_home_path() is the most reliable way to find the web root.
        if (!function_exists('get_home_path')) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        if (!function_exists('get_home_path')) {
            // Fallback: try DOCUMENT_ROOT
            $root = isset($_SERVER['DOCUMENT_ROOT']) ? rtrim((string)$_SERVER['DOCUMENT_ROOT'], '/\\') . DIRECTORY_SEPARATOR : '';
            if ($root === '' || !is_dir($root)) {
                self::set_admin_error('Konnte das Webroot nicht bestimmen. Bitte /wartungsmodus manuell anlegen.');
                return;
            }
            $homePath = $root . DIRECTORY_SEPARATOR;
        } else {
            $homePath = get_home_path();
        }

        $dir = rtrim($homePath, '/\\') . DIRECTORY_SEPARATOR . 'wartungsmodus' . DIRECTORY_SEPARATOR;

        // Ensure directory
        if (!is_dir($dir)) {
            if (!@wp_mkdir_p($dir)) {
                self::set_admin_error('Konnte den Ordner /wartungsmodus nicht erstellen (fehlende Schreibrechte im Webroot).');
                return;
            }
        }

        $viewPath = BSCS_PLUGIN_DIR . 'views/public-page.php';
        if (!file_exists($viewPath)) {
            self::set_admin_error('Template-Datei fehlt: views/public-page.php');
            return;
        }

        // 1) public-page.php (template) – copied for standalone use
        $tpl = file_get_contents($viewPath);
        if ($tpl === false) {
            self::set_admin_error('Konnte Template nicht lesen: views/public-page.php');
            return;
        }

        // 2) index.php (bootstrap + headers + include public-page.php)
        $indexPhp = "<?php\n" .
            "/**\n" .
            " * /wartungsmodus – Generated by Baker Street – Coming Soon\n" .
            " * This file is intentionally kept even when the plugin is deactivated.\n" .
            " */\n\n" .
            "if (!headers_sent()) {\n" .
            "  header('X-Robots-Tag: noindex, nofollow, noarchive', true);\n" .
            "}\n\n" .
            "// Try to bootstrap WordPress so options can be read (works for Bedrock + Classic).\n" .
            "if (!function_exists('get_option')) {\n" .
            "  \$candidates = [\n" .
            "    __DIR__ . '/../wp-load.php',\n" .
            "    __DIR__ . '/../wp/wp-load.php',\n" .
            "    __DIR__ . '/../wordpress/wp-load.php',\n" .
            "  ];\n" .
            "  foreach (\$candidates as \$file) {\n" .
            "    if (is_string(\$file) && file_exists(\$file)) {\n" .
            "      require_once \$file;\n" .
            "      break;\n" .
            "    }\n" .
            "  }\n" .
            "}\n\n" .
            "if (function_exists('nocache_headers')) { nocache_headers(); }\n" .
            "if (function_exists('status_header')) { status_header(503); }\n\n" .
            "require __DIR__ . '/public-page.php';\n";

        // 3) index.html fallback (no PHP execution) – uses defaults, still noindex
        $indexHtml = "<!doctype html><html lang=\"de\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"robots\" content=\"noindex,nofollow,noarchive\"><title>Wartungsmodus</title></head><body>Wartungsmodus</body></html>";

        $writeOk = true;
        $writeOk = $writeOk && @file_put_contents($dir . 'public-page.php', $tpl) !== false;
        $writeOk = $writeOk && @file_put_contents($dir . 'index.php', $indexPhp) !== false;
        $writeOk = $writeOk && @file_put_contents($dir . 'index.html', $indexHtml) !== false;

        if (!$writeOk) {
            self::set_admin_error('Konnte /wartungsmodus Dateien nicht schreiben (fehlende Schreibrechte).');
            return;
        }

        // success -> clear any previous error
        delete_option('bscs_admin_error');
    }

    private static function set_admin_error(string $msg): void {
        update_option('bscs_admin_error', $msg, false);
    }

    public static function admin_notices(): void {
        if (!current_user_can('manage_options')) {
            return;
        }
        $err = get_option('bscs_admin_error');
        if (!is_string($err) || $err === '') {
            return;
        }
        echo '<div class="notice notice-warning"><p>';
        echo '<strong>Baker Street – Coming Soon:</strong> ' . esc_html($err) . ' '; 
        echo 'Die Wartungsseite sollte dennoch über den Plugin-Modus funktionieren, aber <code>/wartungsmodus</code> ist evtl. nicht verfügbar.';
        echo '</p></div>';
    }
}
